rm(list=ls())
dailykos=read.csv("C:/users/zahid/downloads/dailykos.csv")
str(dailykos)
distances=dist(dailykos[2:1546], method="euclidean")
str(distances)
cluster=hclust(distances, method="ward")
str(cluster)
plot(cluster)
clusterGroups=cutree(cluster,k=7)
cluster1=subset(dailykos, clusterGroups==1)
cluster2=subset(dailykos, clusterGroups==2)
cluster3=subset(dailykos, clusterGroups==3)
cluster4=subset(dailykos, clusterGroups==4)
cluster5=subset(dailykos, clusterGroups==5)
cluster6=subset(dailykos, clusterGroups==6)
cluster7=subset(dailykos, clusterGroups==7)
nrow(cluster1)
nrow(cluster6)
tail(sort(colMeans(cluster1[-1])))
tail(sort(colMeans(cluster7[-1])))

set.seed(1000)
KMC=kmeans(dailykos[2:1546],centers=7)
str(KMC)
dailykosCluster=KMC$cluster
KMC$centers[1]
table(dailykosCluster)
kcluster7=subset(dailykos,KMC$cluster==7)
tail(sort(colMeans(kcluster7[-1])))
table(clusterGroups,KMC$cluster)
table(clusterGroups)
