rm(list=ls())
wiki=read.csv("C:/Users/Zahid/Downloads/wiki.csv", stringsAsFactor=FALSE)
str(wiki)
wiki$Vandal=as.factor(wiki$Vandal)
table(wiki$Vandal)
library(tm)
corpusAdded= Corpus(VectorSource(wiki$Added))
corpusAdded[[1]]
corpusAdded= tm_map(corpusAdded, tolower)
corpusAdded= tm_map(corpusAdded, removePunctuation)
corpusAdded=tm_map(corpusAdded, removeWords, stopwords("english"))
corpusAdded=tm_map(corpusAdded, stemDocument)
dtmAdded= DocumentTermMatrix(corpusAdded)
dtmAdded
length(stopwords("english"))
sparseAdded=removeSparseTerms(dtmAdded, 0.997)
sparseAdded
wordsAdded=as.data.frame(as.matrix(sparseAdded))
wordsAdded
colnames(wordsAdded) = paste("A", colnames(wordsAdded))
wordsAdded
corpusRemoved=Corpus(VectorSource(wiki$Removed))
corpusRemoved=tm_map(corpusRemoved, tolower)
corpusRemoved=tm_map(corpusRemoved, removePunctuation)
corpusRemoved=tm_map(corpusRemoved, removeWords, stopwords("english"))
corpusRemoved= tm_map(corpusRemoved, stemDocument)
corpusRemoved
dtmRemoved=DocumentTermMatrix(corpusRemoved)
sparseRemoved=removeSparseTerms(dtmRemoved, 0.997)
wordsRemoved=as.data.frame(as.matrix(sparseRemoved))
str(wordsRemoved)
colnames(wordsRemoved)= paste("R",colnames(wordsRemoved))
wikiWords=cbind(wordsAdded, wordsRemoved)
wikiWords
wikiWords$Vandal=wiki$Vandal
str(wikiWords)
set.seed(123)
library(caTools)
split=sample.split(wikiWords$Vandal,0.7)
table(wikiWords$Vandal)
train=subset(wikiWords, split==TRUE)
test=subset(wikiWords,split==FALSE)
table(test$Vandal)
CART=rpart(Vandal~., data=train, method="class")
pred= predict(CART, newdata=test, type="class")

pred.prob=pred[,2]
str(test$Vandal)
table(test$Vandal, pred)
prp(CART)
table(wiki$Vandal)
wikiWords2 = wikiWords
wikiWords2$HTTP = ifelse(grepl("http",wiki$Added,fixed=TRUE), 1, 0)
table(wikiWords2$HTTP)
wikiTrain2 = subset(wikiWords2, split==TRUE)
wikiTest2 = subset(wikiWords2, split==FALSE)
CART1=rpart(Vandal~., data=wikiTrain2, method="class")
pred1= predict(CART1, newdata=wikiTest2, type="class")
table(wikiTest2$Vandal, pred1)
wikiWords2$NumWordsAdded = rowSums(as.matrix(dtmAdded))
wikiWords2$NumWordsRemoved = rowSums(as.matrix(dtmRemoved))
sum(wikiWords2$NumWordsAdded)
train1=subset(wikiWords2,split==TRUE)
test1=subset(wikiWords2, split==FALSE)
CART3=rpart(Vandal~., data=train1, method="class")
pred3= predict(CART3, newdata=test1, type="class")
table(test1$Vandal, pred3)
wikiWords3 = wikiWords2
wikiWords3$Minor = wiki$Minor
wikiWords3$Loggedin = wiki$Loggedin
train4=subset(wikiWords3, split==TRUE)
test4=subset(wikiWords3, split==FALSE)
CART4=rpart(Vandal~.,data=train4, method="class")
pred4=predict(CART4, newdata=test4, type="class")
table(test4$Vandal, pred4)
prp(CART4)
