# Tree logistic regression
rm(list=ls())
stevens=read.csv("C:/Users/zahid/Downloads/stevens.csv")
str(stevens)
library(caTools)
set.seed(3000)
split=sample.split(stevens$Reverse, SplitRatio=0.7)
Train= subset(stevens, split==TRUE)
Test= subset(stevens, split==FALSE)
install.packages("rpart")
library(rpart)
install.packages("rpart.plot")
library(rpart.plot)
StevensTree=rpart(Reverse~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="class", control=rpart.control(minbucket=25))
prp(StevensTree)
PredictCART= predict(StevensTree, newdata=Test, type="class")
table(Test$Reverse, PredictCART)
library(ROCR)
PredictROC= predict(StevensTree, newdata=Test)
PredictROC
pred=prediction(PredictROC[,2], Test$Reverse)
perf= performance(pred, "tpr", "fpr")
plot(perf)
as.numeric(performance(pred, "auc")@y.values)
StevensTree1=rpart(Reverse~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="class", control=rpart.control(minbucket=5))
prp(StevensTree1)
StevensTree2=rpart(Reverse~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data=Train, method="class", control=rpart.control(minbucket=100))
prp(StevensTree2)
install.packages("randomForest")
library(randomForest)
StevensForest = randomForest(Reverse ~ Circuit + Issue+Petitioner+Respondent + LowerCourt+Unconst, data=Train, nodesize=25, ntree=200)
Train$Reverse= as.factor(Train$Reverse)
Test$Reverse= as.factor(Test$Reverse)
StevensForest = randomForest(Reverse ~ Circuit + Issue+Petitioner+Respondent + LowerCourt+Unconst, data=Train, nodesize=25, ntree=200)
PredictForest= predict(StevensForest, newdata=Test)
table(Test$Reverse, PredictForest)
set.seed(200)
StevensForest = randomForest(Reverse ~ Circuit + Issue+Petitioner+Respondent + LowerCourt+Unconst, data=Train, nodesize=25, ntree=200)
PredictForest= predict(StevensForest, newdata=Test)
table(Test$Reverse, PredictForest)
install.packages("caret")
library(caret)
install.packages("e1071")
library(e1071)
fitControl= trainControl(method="cv", number=10)
cartGrid= expand.grid(.cp=(1:50)*0.01)
?expand.grid
train(Reverse~ Circuit+ Issue + Petitioner + Respondent + LowerCourt + Unconst , data = Train, method="rpart", trControl=fitControl, tuneGrid=cartGrid)
StevensTreeCV = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, method="class", data=Train, control= rpart.control(cp=0.18))
prp(StevensTreeCV)
PredictCV= predict(StevensTreeCV, newdata=Test, type="class")
table(Test$Reverse, PredictCV)

