rm(list=ls())
letters= read.csv("C:/Users/Zahid/Downloads/letters_ABPR.csv")
str(letters)
letters$isB=as.factor(letters$letter=="B")
library(caTools)
set.seed(1000)
split=sample.split(letters$isB, SplitRatio=0.5)
table(split)
train=subset(letters, split==TRUE)
test=subset(letters, split==FALSE)
table(test$isB)
CARTb = rpart(isB ~ . - letter, data=train, method="class")
summary(CARTb)
pred= predict(CARTb, newdata=test, method="class")
table(test$isB)
table(test$isB, pred)

PredictROC= predict(CARTb, newdata=test, type="class")
table(PredictROC, test$isB)
library(randomForest)
set.seed(1000)
forest=randomForest(isB ~ .-letter, data=train)
pred=predict(forest, newdata=test)
table(test$isB, pred)
letters$letter = as.factor( letters$letter )
str(letters)
set.seed(2000)
split=sample.split(letters$letter, SplitRatio=0.5)
train=subset(letters, split==TRUE)
test=subset(letters, split==FALSE)
table(test$letter)
model=rpart(letter~.-isB, data=train, method="class")
summary(model)
pred=predict(model, newdata=test, type="class")
str(pred)
str(test)
table(test$letter, pred)
nrow(test)
forest= randomForest(letter ~.-isB,data=train, method="class")
pred=predict(forest, newdata=test, type="class")
table(test$letter, pred)






