# Predicting votes
gerber=read.csv("C:/Users/Zahid/Downloads/gerber.csv")
str(gerber)
table(gerber$voting)
temp=subset(gerber, gerber$neighbors==1 & gerber$voting==1)
temp=subset(gerber, gerber$civicduty==1 & gerber$voting==1)
temp=subset(gerber, gerber$hawthorne==1 & gerber$voting==1)
temp=subset(gerber, gerber$self==1 & gerber$voting==1)
str(temp)
mod=lm(voting~ neighbors+civicduty+hawthorne+self, data=gerber)
mod1=glm(voting~ neighbors+civicduty+hawthorne+self, data=gerber, family=binomial)
summary(mod)
pred=predict(mod)
pred1=predict(mod1, type="response")
summary(pred)
summary(pred1)
table(gerber$voting, pred>=0.3)
table(gerber$voting, pred>=0.5)
table(gerber$voting)
library(ROCR)
predROCR=prediction(pred1, gerber$voting)
ROCRperf=performance(predROCR,'tpr','fpr' )
attributes(performance(predROCR, 'auc'))$y.values[[1]]
plot(ROCRperf)
library(rpart)
library(rpart.plot)
CARTmodel = rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber)
prp(CARTmodel)
CARTmodel2 = rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber, cp=0.0)
CARTmodel3 = rpart(voting ~ civicduty + hawthorne + self + neighbors+sex, data=gerber, cp=0.0)
prp(CARTmodel2)
pred1=predict(CARTmodel)
summary(pred1)
prp(CARTmodel3)
str(gerber)
CARTmodel4 = rpart(voting ~ control, data=gerber, cp=0.0)
CARTmodel5 = rpart(voting ~ control+sex, data=gerber, cp=0.0)
?abs
pred2=predict(CARTmodel4)
pred2
prp(CARTmodel4, digits=6)
abs(0.296638-0.34)
mod3=glm(voting~control + sex, data=gerber, family=binomial)
summary(mod3)
Possibilities = data.frame(sex=c(0,0,1,1),control=c(0,1,0,1))
predict(mod3, newdata=Possibilities, type="response")
LogModel2 = glm(voting ~ sex + control + sex:control, data=gerber, family="binomial")
summary(LogModel2)
predict(LogModel2, newdata=Possibilities, type="response")